### ISSUE TITLE
v1.0.0 broke custom flight repos logical flights

### ISSUE THREAD

**Issue by Apollorion** [Apollorion/fly#33]
Im not sure why, but any logical flight is throwing this error when read from a custom flight repo:

```
main.js:58 Uncaught (in promise) TypeError: logics is not iterable
    at main.js:58:35
    at Generator.next (<anonymous>)
    at main.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (main.js:3:12)
    at handleFlight (main.js:51:12)
    at main.js:31:23
    at Generator.next (<anonymous>)
    at fulfilled (main.js:4:58)
```

Getting this error when using my joey_repo.json repo. Maybe its formatted incorrectly? I need to figure that out.

**Comment by Apollorion** [comment]
Nope, didnt get broken. I just setup my custom repo incorrectly.
